# Generated by Django 3.1.2 on 2024-09-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
