XXXX XXXXXXXX XXXXXXX XXXXXXXX
BBBB BBBBBB
 XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
       XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX XXXXXX
             XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXX
       XXXXXX
       XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          BBB BBBBBBBB BB BBBBBBBBBB
            XXXX XXXXXXXXXXXXX
             XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX

                   XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX

                      XXXX
                         XXX XXBBBBBB BBBBBBBBBBBBBBX
                         XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                         XXXXXXXXXXX XXXXXXXXXX XX
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXX
                XXXXXX
             XXXX
          XXXXXX
          BBBBBB
         XXXXXX
    XXXXXX
 XXXXXXXXXX
