BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXXX
     XXXXXX
        XXXX XXXXXXXX XXXX XXXX XXX
        XXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
       XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXX
        XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX

        XXXX XXXXXXX XXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX

        XXXX XXXX XXX XXX
        XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
       
        XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

        XXXX XXXXX XXX XXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
       
        XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
           XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XX XXX
           XXXXXXXX XXXXXX X
              XXXXXXXXXXXXXXXXXXXXXXXXXX
           X
           XXXXXXXXXX XXX XXXXXXXX

           XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXX XXX XX XX XX XX XX XX X
              XXXX X
                 XXXX XX
                 XXXXXXXX XX X
                    XXXXXXX X XXXXXX XX XXXXXXXXXXXXXXXXXXXX
                 XX
              X X XXXXXXXXXXXXXXXXXXX
              XXXXXXX X XX
              XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
              X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
           XXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXX
        XXXXXXX
     XXXXXX
    
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
         BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXX

        XXXX XXXX XX XXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

        XXXX XXXXX XX XXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX
XXXXXXX
